plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.1'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.minhyuck'
version = '0.0.1-SNAPSHOT'
description = 'labs-api'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

sourceSets {
    main {
        resources {
            srcDirs = ['src/main/resources', 'src/main/java']
            exclude '**/*.java'
        }
    }
}

dependencies {
    /* Spring Boot */
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'        // REST API (Tomcat 포함)
    implementation 'org.springframework.boot:spring-boot-starter-validation'    // Validation
    implementation 'org.springframework.boot:spring-boot-starter-actuator'      // 헬스체크
    runtimeOnly 'io.micrometer:micrometer-registry-prometheus'                  // Prometheus registry
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.1.0'    // Swagger UI
    developmentOnly 'org.springframework.boot:spring-boot-docker-compose'       // 로컬 Run 시 Docker Compose 자동화 (Postgres 연동)

    /* DB */
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'            // DataSource
    implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:4.0.0'    // MyBatis
    implementation 'org.springframework.boot:spring-boot-starter-flyway'          // Flyway
    runtimeOnly 'org.flywaydb:flyway-database-postgresql'                         // Flyway 12+ Postgres dialect
    runtimeOnly 'org.postgresql:postgresql'                                       // Postgres 드라이버

    /* Lombok · 설정 메타데이터 */
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

    /* Test */
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'        // REST API (Tomcat 포함)
    testImplementation 'org.springframework.boot:spring-boot-starter-validation-test'    // Validation
    testImplementation 'org.springframework.boot:spring-boot-starter-actuator-test'      // 헬스체크
    testRuntimeOnly 'com.h2database:h2'                                                  // Test profile in-memory
    testCompileOnly 'org.projectlombok:lombok'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testAnnotationProcessor 'org.projectlombok:lombok'
}

tasks.named('test') {
    useJUnitPlatform()
}
