spring:
  datasource:
    url: ${LABS_DATASOURCE_URL:jdbc:postgresql://localhost:5432/labs_api}
    username: ${LABS_DATASOURCE_USERNAME:labs}
    password: ${LABS_DATASOURCE_PASSWORD:labs}
    driver-class-name: org.postgresql.Driver

management:
  endpoint:
    health:
      show-details: always
